### ISSUE TITLE
Firefox Based Browsers Probably Incompatible

### ISSUE THREAD

**Issue by SQueen2k1** [bethylamine/soupcan#1]
Loading the extension on any firefox based browsers are giving a error like this:

```
There was an error during the temporary add-on installation.
Error details

background.service_worker is currently disabled
```
I believe it's because firefox does not use background.service_worker but instead background.scripts

**Comment by bethylamine** [comment]
Seems like Chrome isn't happy with `background.scripts` and Firefox doesn't support `background.service_worker` and wants `background.scripts`. ([source](https://stackoverflow.com/questions/75043889/manifest-v3-background-scripts-service-worker-on-firefox))

I may try to create a `manifest-v2` version in the mean time for Firefox users, until `v3` is supported. Google doesn't even accept new extensions using manifest v2 any more.

**Comment by bethylamine** [comment]
Could you try changing `service_worker: "background.js"` to `"scripts": ["background.js"]` and see if that works?

**Comment by DeathGod2k1** [comment]
Yea that works, then you just need to go to the extension settings on firefox (while twitter is open) to allow it to always run

**Comment by DeathGod2k1** [comment]
In the new version the option to manually update the database is non existant

**Comment by SQueen2k1** [comment]
When submitting reports this error happens:

`Failed to submit report: 
TypeError: NetworkError when attempting to fetch resource.`

**Comment by bethylamine** [comment]
Got it! Thanks for the help. It looks like it might be CORS related? Although it should be sending back the right CORS headers, it works in Chrome. Hm. I also notice right-clicking on the background of the page doesn't show the other context menu items, so I may have to also add them to the plugin button

**Comment by bethylamine** [comment]
May be like this https://stackoverflow.com/a/49098515

**Comment by SQueen2k1** [comment]
> May be like this https://stackoverflow.com/a/49098515

Yes, seems the reports have to be fixed not through the extension but in the backend, give it some sort of CORS handling, chrome doesn't care about it but firefox won't work without it.

**Comment by bethylamine** [comment]
Okay, I pushed some changes which should help Firefox. You still need to remember to give it permission to run on twitter via the "Manage extensions" page. Let me know how it goes!

**Comment by SQueen2k1** [comment]
> Okay, I pushed some changes which should help Firefox. You still need to remember to give it permission to run on twitter via the "Manage extensions" page. Let me know how it goes!

Can confirm, both automated database download and reporting works now

**Comment by bethylamine** [comment]
Firefox compatibility seems to be stable for now. Closing.
