### ISSUE TITLE
A button to block all red users who have interacted with a tweet

### ISSUE THREAD

**Issue by hasrock36** [bethylamine/soupcan#100]
I'm not sure how viable this is to setup, but a way to block a bunch of red users at once, without having to block every single one (I do occasionally find false positives) would be helpful, currently I have to manually hit block several times, it would be convenient to see a tweet being swarmed by transphobes and block en masse

**Comment by bethylamine** [comment]
An integration with BlueBlocker was done here https://github.com/kheina-com/Blue-Blocker/issues/139
