### ISSUE TITLE
Send Report dialog not appearing in Firefox

### ISSUE THREAD

**Issue by davidallsopp** [bethylamine/soupcan#101]
I have soupcan working fine in Chromium, but on Firefox only some of the right-click menu options work.

"Search tweets for gender-related keywords" works fine, opening a new tab with search results as expected.

"Report transphobe" does not work, however. Nothing happens when I select this menu item - the Send Report dialog does not appear.

Colours seem to be applied correctly to marked accounts, along with the labels in profiles e.g. "[Marked in Shinigami Eyes]"

Both browsers are running on the same machine on the same IP address and same internet connection, but with a different Twitter user logged in for each browser.

I also have Shinigami Eyes running in both browsers, but disabling it doesn't make any difference to the problem in Firefox.

Chromium Version 121.0.6167.139 (Official Build) snap (64-bit)
Firefox  122.0.1 (64-bit), Mozilla Firefox snap for Ubuntu, canonical-002 - 1.0

Ubuntu Linux 22.04.3 LTS

**Comment by davidallsopp** [comment]
No, doesn't seem to be - it's happening to me with the browser window maximised (1920 x 1200).

**Comment by bethylamine** [comment]
If you haven't already, could you try uninstalling and re-installing the plugin?

Other than that- if you could go to Debug Add-ons -> Soupcan [Inspect] -> Console, to see if there are any errors there?

![image](https://github.com/bethylamine/soupcan/assets/130214958/ea1a61ab-aa8a-4020-819e-0352f689d771)

![image](https://github.com/bethylamine/soupcan/assets/130214958/f8405fb2-8d1a-4f48-a105-ad4858038fd8)

![image](https://github.com/bethylamine/soupcan/assets/130214958/50c447bf-5a51-45d7-962d-3919b0005f75)

**Comment by davidallsopp** [comment]
I've uninstalled all extensions, reinstalled Soupcan, but getting the same problem. 

The debug console showed one warning (but that was in the background before I actually did anything). 

Selecting the "Report Transphobe" menu item does nothing, as before, and no further errors appear in the debug console: 
![image](https://github.com/bethylamine/soupcan/assets/5507886/f8b5b214-e57d-4924-add4-f86c05b620c5)

**Comment by bethylamine** [comment]
Should be fixed in 0.17.2. I used a hacky workaround to try to grab the page theme, by stealing it from the "DM drawer" that shows up in the bottom right, but it's not always there like I thought it was. I switched it to grab it from the document body and it worked, so. That should be that

**Comment by davidallsopp** [comment]
Upgraded and now working for me - thank you!
