### ISSUE TITLE
Trends text leaking into transphobe counter widget

### ISSUE THREAD

**Issue by qtlunya** [bethylamine/soupcan#110]
<img width="369" alt="Transphobe counter - Following - Premier Le
(scroll down to count more) 0 / 785 (0%). List of trends below mentions Premier League." src="https://github.com/bethylamine/soupcan/assets/148620615/3ec08035-a3ca-47b6-8d00-d9362202a787">

**Comment by bethylamine** [comment]
I'm not sure how useful this widget is any more because you can't scroll through someone's entire follow list any more anyway
