### ISSUE TITLE
Stop using Shinigami Eyes; standards are incompatible

### ISSUE THREAD

**Issue by JapanYoshi** [bethylamine/soupcan#113]
The Shinigami Eyes list is as flawed as its guidelines, which have such sensitive and subjective thresholds as [“transmedicalism”](https://shinigami-eyes.github.io) to qualify as “transphobic”, which [Soupcan’s guidelines](https://bethylamine.github.io/library/browser-extension/mod) do not recognize as such.

In addition, Shinigami Eyes is made from data that is kept insecurely and without consent; there is a reason why it was banned in Norway. Using the same ill-gotten data could get this extension also banned there.

I find it wisest to discard all data from Shinigami Eyes, scrub any mentions of Shinigami Eyes, and deny association with Shinigami Eyes in general.

Related to #102

**Comment by bethylamine** [comment]
Shinigami Eyes list has been removed from Soupcan.
