### ISSUE TITLE
Report strengths

### ISSUE THREAD

**Issue by bethylamine** [bethylamine/soupcan#115]
By giving users an indication of the strength of a report (was it based on multiple tweets? Was it a unilateral decision by a moderator? Are there no recent reports?) as a percentage or etc., people can make a more informed decision about the nature of reporting that has been done on that user. That may also encourage people to add new reports for low-strength reported users, to add more examples when they are seen. Right now there is basically no incentive to reporting a red user even if adding more examples would be an improvement in accountability.

**Comment by numarknuleo** [comment]
One consideration may also be a "decaying" transphobia score. I.e., if the reports are fairly old, the Soupcan-flagged account's transphobia rating starts to decline until it reaches a pre-determined value, at which point they get marked as yellow (or a faded red). Adding new reports would increase the score, and moderators, Beth, etc. entries would never decay. The main downside being that this could allow some transphobes to "game the system" by evading reports over long periods of time, but that could be offset by the fact that, well, they're not making transphobic tweets during that time period.
