### ISSUE TITLE
Soupcan Wants Browser History

### ISSUE THREAD

**Issue by zig13** [bethylamine/soupcan#119]
Seemingly as of version 0.21.2, Soupcan now requires access to "Read your browsing history".
I could not find an explanation for this additional access requirement on the website, this Github, or [@bethylamine](https://twitter.com/bethylamine).
![Annotation 2024-04-02 170120](https://github.com/bethylamine/soupcan/assets/659983/640cc0bc-8d71-4bae-98a8-620a922c2f3a)
![Annotation 2024-04-02 170147](https://github.com/bethylamine/soupcan/assets/659983/5bc8a0ec-2323-4f50-b8d5-67770ff6354b)

**Comment by bethylamine** [comment]
This is for a feature for mobile browsers for a way to ask for permissions when you navigate to either twitter.com or x.com. It's not needed for desktop users and it doesn't read your history.

@INSANEMODE - I'll work with you to use the previous implementation that doesn't require this permission

**Comment by bethylamine** [comment]
Other example popups

![image](https://github.com/bethylamine/soupcan/assets/130214958/53380711-aca8-4a43-bef4-98a6bf22619d)
![image](https://github.com/bethylamine/soupcan/assets/130214958/e6105a7b-f800-46ba-80d7-93fe148a4940)

**Comment by INSANEMODE** [comment]
> This is for a feature for mobile browsers for a way to ask for permissions when you navigate to either twitter.com or x.com. It's not needed for desktop users and it doesn't read your history.
> 
> @INSANEMODE - I'll work with you to use the previous implementation that doesn't require this permission

Ah, yeah we can do that, just adding it back as an option in the settings menu for now, instead of checking to see if you are on Twitter?

At least most new users will be covered by the setup. Only people that upgrade without the needed host permissions would really need to use it. 

And that should be a pretty small percentage of mobile users.

**Comment by bethylamine** [comment]
Did you see the pull request?

**Comment by INSANEMODE** [comment]
Oh, yeah. I saw it right after making the comment. Will test in a minute.

**Comment by bethylamine** [comment]
This has been fixed in v0.22.0 which is due to release on the web stores.
