### ISSUE TITLE
Make "redacted" text not a link in reports list

### ISSUE THREAD

**Issue by numarknuleo** [bethylamine/soupcan#123]
For non-moderators, clicking on the list of reports on a user's profile page shows "redacted (only visible to mods)" under the "reporter" column. However, this is a clickable link to a non-existent user with the URL https://twitter.com/redacted%20(only%20visible%20to%20mods) and, as a result, clicking this link brings you to a Twitter error page, as there is no user with the username "redacted (only visible to mods)". This is a minor issue, but one that still breaks the flow of navigation if you accidentally/absentmindedly click on this link as a non-moderator. Making the "reporter" link clickable only if you are a mod would remove this issue.

![image](https://github.com/bethylamine/soupcan/assets/5513931/9f7d5be7-2677-47b1-85b4-b3d324ca6fa1)

**Comment by bethylamine** [comment]
I made a server-side change to make the reporter blank instead of "redacted..." - does that fix the issue satisfactorily?

**Comment by bethylamine** [comment]
e.g.

![image](https://github.com/bethylamine/soupcan/assets/130214958/5f3b4969-f2dd-4ea9-8c9f-7d917b50f0ad)

**Comment by bethylamine** [comment]
closing for now, please re-open if it doesn't work
