### ISSUE TITLE
Color blindness scheme options display broken

### ISSUE THREAD

**Issue by numarknuleo** [bethylamine/soupcan#124]
Using: Firefox 124.0.2 and Soupcan 0.22 (not tested on other browsers, so may exist in others as well)

The color blindness scheme options section does not show any highlighted/red text whatsoever in the above browser/Soupcan extension version. Changing the color-blindness type in the drop-down box does not display any changes, as it appears that the text is simply not being styled at all.

![image](https://github.com/bethylamine/soupcan/assets/5513931/7f2af8da-1ea5-4138-8e8d-e687b539f02d)

**Comment by numarknuleo** [comment]
May be related to this error in the Firefox console (it appears to be trying to load Bootstrap as a local resource, potentially?)

![image](https://github.com/bethylamine/soupcan/assets/5513931/870916a6-5647-4070-a550-70e1a480d723)

**Comment by bethylamine** [comment]
![image](https://github.com/bethylamine/soupcan/assets/130214958/4d4883dd-70f3-4182-b212-a4f3cd426789)

![image](https://github.com/bethylamine/soupcan/assets/130214958/70b93dff-cce3-40de-888b-679bed39d91c)

![image](https://github.com/bethylamine/soupcan/assets/130214958/60c0fe89-973d-477d-b065-acad76c8cf06)

It seems to work on Twitter itself but not in the examples, is that also your experience?

**Comment by bethylamine** [comment]
fixed in 0.22.3
