### ISSUE TITLE
Having trouble with still seeing posts from a transphobe when they post a gif

### ISSUE THREAD

**Issue by iansquenet** [bethylamine/soupcan#130]
![image](https://github.com/bethylamine/soupcan/assets/36297463/390ecc94-e834-4e16-80c8-ac392014a248)

**Comment by iansquenet** [comment]
Seems that some text posts don't get blurred too.

**Comment by bethylamine** [comment]
Interesting, this seems to be a regression based on a change to how posts are detected (when the feature to completely hide tweets was introduced, no doubt.) I'll look into it. Thanks!
