### ISSUE TITLE
Extension intermittently stops working

### ISSUE THREAD

**Issue by luxploit** [bethylamine/soupcan#142]
As of yesterday I've started noticing a strange bug. Sometimes when Soupcan runs a database update it will stop working entirely, which can be resolved by just disabling and re-enabling the extension. But theres also another bug like is shown in the video where the extension is loaded but doesn't do anything. When that happens I have to remove it, restart my browser and re-download it.

I'm using Floorp 11.14.1

https://github.com/bethylamine/soupcan/assets/113054610/607b20c9-2b3a-47c4-980a-cdf608e5fb7e

**Comment by bethylamine** [comment]
Could you open a developer console and see if there are any JavaScript errors there the next time it stops working? It seems like maybe something on the extension backend died

**Comment by luxploit** [comment]
This stopped happening a while ago, I posted the initial issue over 3 months
