### ISSUE TITLE
Account and Report reasons mismatching

### ISSUE THREAD

**Issue by Emix33** [bethylamine/soupcan#148]
For me, when looking at the twitter account of (at) DeadEyedVVitch that person is highlighted red. While I dont know if that is accurate, when looking at the reasons, all reasons cite tweets by a different (definitely transphobic) account. Looking at that accound and the Reasons showed that they were completely identical. When I accessed the original account later again, the reasons listed were different and again all refered to a different account (not the same as before though) with the exact same reasons shown when accessing that account. This seems to me like either some weird database corruption (though I have redownloaded it multiple times, same result) or some other technical error.

**Comment by Emix33** [comment]
For me the issue occurs in both Firefox and Chrome

**Comment by bethylamine** [comment]
Very weird. Thanks for the report. If you find any other users this happens to please add them here

**Comment by bethylamine** [comment]
Screenshots would also be great

**Comment by Emix33** [comment]
![Screenshot (1877)-e](https://github.com/user-attachments/assets/8dc25f61-7df5-4538-af45-17847cf921a9)

**Comment by Emix33** [comment]
Unfortunately I didnt take a picture the first time this occured but there were other reasons (more than now) all refering to a different transphobic account (I forgot the name/handle but it was a well known one).
It would also be good to know if this issue is replicable outside of my pc, to rule out any kind of local cache.

**Comment by bethylamine** [comment]
<img width="818" alt="image" src="https://github.com/user-attachments/assets/f333606a-59ab-401e-8ffa-58e3c3c3daca">

Yes I also see that

**Comment by Emix33** [comment]
![Screenshot (1878)-e](https://github.com/user-attachments/assets/dde533a4-50f8-439b-9fa4-c3f4e078322a)
I remembered the first transphobic account that was shown in the reasons before, when looking at that account directly now, it seems to also be broken though (at least the resons listed are). This could however also be because I tried appealing the original reasons on the (assumed) non-transphobic account.

**Comment by bethylamine** [comment]
seems to be happening for every red account, looks like a general caching issue. i'll fix

**Comment by bethylamine** [comment]
should be fixed now. thanks!

**Comment by Emix33** [comment]
I can confirm that the issue is fixed. However the reasons that are listed now seem to not be transphobic? They seem to be a bit hostile and definitely controversial but not transphobic.

**Comment by bethylamine** [comment]
my opinion, not coming after you: the comments i see are reducing their identity to (cis coded) masculinity, deliberately isolating it from their trans identity. when you remove someone's transness to deride them or invalidate them, that is transphobic

<img width="804" alt="image" src="https://github.com/user-attachments/assets/c9f32aae-dba0-4b23-a1b2-2c045751687e">

**Comment by Emix33** [comment]
Ok, I can partly understand/accept that. It should however be possible to critigue peoples masculinity/femininity even if they are trans. As a trans person myself, being trans shouldnt shield me from criticism for my behaviors (no matter what gender those behaviors are coded as). While that person as a whole seems to be marked correctly, some! of the reasons listed do not seem to be completely isolating someone to their (cis coded) masculinity but rather just focusing on that specific displayed behavior. It should not be necessary for every critisism to contain a nuanced explanation on how this behavior is generally just a part of a (trans) persons identity.
