### ISSUE TITLE
Content not always masked if only quoted user is red

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#16]
If an unmarked user quotes a red/yellow user, sometimes the quoted tweet's contents are not masked, for example here:

https://twitter.com/DrLoupis/status/1653647614900838400/retweets/with_comments

It also never seems to apply the full masking to quoted tweets, only media masking, but even that doesn't work sometimes.

**Comment by bethylamine** [comment]
Getting masking to apply correctly to every single different case is going to be the death of me lol
