### ISSUE TITLE
Possible to click "Send report" twice

### ISSUE THREAD

**Issue by bethylamine** [bethylamine/soupcan#18]
Accidentally double clicked "send report" and it sent two reports. It's not a big issue but it should disable the button on the first click.

**Comment by ThienBNguyen** [comment]
Hi Bethylamine, I am interested in the issue. can I try to solve it? thanks

**Comment by Anurag-Raut** [comment]
> double clicked "send report" a

I have loaded the extension as mentioned in the readme , but on right clicking on any username I don't see soupcan options

**Comment by Anurag-Raut** [comment]
@bethylamine Please review PR #19 and let me know if any changes is to be done.
