### ISSUE TITLE
Color sticks around after switching to another account

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#2]
When I report an account as a transphobe and then switch to another account, e.g. from the "You might like" sidebar, the color seems to stick around on the new account, and when trying to report it it says "[previous account's username] is already souped". The "[Reported by you]" note is not there, however. A reload fixes it.

**Comment by bethylamine** [comment]
Confirmed, but only seems to happen when it's orange

**Comment by bethylamine** [comment]
Should be fixed by fc2cac60411087f8a5726fee2da31bf1fb2d052f
