### ISSUE TITLE
Some tweets from unmarked users in reply/quote to transphobes are incorrectly masked

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#23]
For example recent retweets from these users:
* https://twitter.com/errorsimulator
* https://twitter.com/binikitty (this one has been marked as transphobic in meantime)

<img width="600" alt="Screenshot of masked retweet from @errorsimulator" src="https://user-images.githubusercontent.com/482367/236213599-7aa23eb2-8c9a-4722-8624-3ad275ea6b10.png">
<img width="602" alt="Screenshot of unmasked retweet from @errorsimulator" src="https://user-images.githubusercontent.com/482367/236213649-d0cb371d-cf5e-4678-bc6e-fc2c6b0609f7.png">
<img width="600" alt="Screenshot of masked retweet from @binikitty" src="https://user-images.githubusercontent.com/482367/236213730-33f5925e-1e7a-4a25-b3b4-ded0839601ab.png">
<img width="602" alt="Screenshot of unmasked retweet from @binikitty" src="https://user-images.githubusercontent.com/482367/236213779-bafac6a5-f342-49c3-8193-8217f7eebf7f.png">

**Comment by bethylamine** [comment]
Thank you for the examples. I might need to switch to a JavaScript-based implementation because the css selectors for these cases are getting _really_ complicated lol.

**Comment by bethylamine** [comment]
_Should_ be fixed by 0958a59077192d1debe623a7d676f3521aa14f31, please retest

**Comment by 0xallie** [comment]
I tested it by serving a local dataset.json with Locke_Wiggins and BiniKitty removed since they were marked as transphobic in meantime. Seems to work fine now.
