### ISSUE TITLE
Orange labels disappear after a while

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#29]
I haven't figured out precisely when/why this happens yet, but it seems like orange labels disappear after a while, even though the report goes through fine, and the users get marked as red about an hour later. Sometimes they also reappear and then disappear again on certain users.

**Comment by bethylamine** [comment]
Hmm, is it maybe when you switch tabs? Right now if you mark someone in a tab and switch to another tab, they don't show up as orange until you refresh (even if you navigate around, because Twitter doesn't actually change page, it just updates the current page)

**Comment by 0xallie** [comment]
It's not just that, sometimes the orange labels disappear and don't come back even after refreshing, even on the same tab where I originally reported them.

**Comment by bethylamine** [comment]
When did this start happening, and could you try with the latest version (0.6.12)? I changed the way that local and DB-sourced labels are evaluated, so it may have changed the behavior of color coding

**Comment by 0xallie** [comment]
Never mind, it happened again.

**Comment by bethylamine** [comment]
It might actually be working as intended, I think some of your reports I appealed because I didn't see a broader pattern of transphobia, but the messaging on that is kind of awkward. Were any of these them do you know? (I think these are the most recent ones?)

![image](https://github.com/bethylamine/soupcan/assets/130214958/cb42d7ba-b5ed-4e81-9d4d-598e8b59ae9e)

**Comment by 0xallie** [comment]
Hmm, I seem to remember them turning red after white, but I don't remember which user it was last time after the update. `@entrappt` sounds like it may have been one of them, but I think that was probably before the update.

Anyway, I'll look over these and DM you with details if I think any should still be marked as transphobic, so as to not clutter this thread.

**Comment by bethylamine** [comment]
They should now appear green instead of going back to white. If this happens again feel free to reopen
