### ISSUE TITLE
Display name/username doesn't become a link for blocked accounts

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#3]
If I'm viewing the profile of a blocked account, the display name/username doesn't become a link until I click "view tweets".

**Comment by 0xallie** [comment]
It seems like this also happens if the user has no tweets (or at least none on the main tab).

**Comment by bethylamine** [comment]
Confirmed

**Comment by bethylamine** [comment]
Should be fixed by fc2cac60411087f8a5726fee2da31bf1fb2d052f
