### ISSUE TITLE
Transphobe counter doesn't show up if there's no "Who to follow" section

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#33]
Sometimes "who to follow" doesn't show up, e.g. if I have the user blocked, or if they're private (even though I follow them). This also makes the transphobe counter not show up.

**Comment by bethylamine** [comment]
Ooh, okay. Hadn't thought of this case. Since the transphobe counter clones the 'who to follow' section. Would you like to have a go at solving this one?

**Comment by bethylamine** [comment]
Does the "What's happening" panel show up all the time at least?
