### ISSUE TITLE
Re-reporting appealed users doesn't work

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#43]
If a user is in appealed state and I report them, the report goes through the queue as normal but the user gets stuck in "appealed" state in the database.

Example account where this happened: `@entrappt`

**Comment by bethylamine** [comment]
Fixed. It was only removing approved appeals if the person self-reported, not if they were reported via the normal (trust-based) method.

https://twitter.com/entrappt is now showing up red for me after updating the DB.

Previous ones will need to be re-reported.
