### ISSUE TITLE
All images are filtered

### ISSUE THREAD

**Issue by hasrock36** [bethylamine/soupcan#46]
irregardless of content masking setting, every image is blocked with an hourglass unless you open the specific tweet.
![image](https://github.com/bethylamine/soupcan/assets/54255452/32fb5010-cdfa-4f54-9aa4-eda6fc1a719a)

**Comment by hasrock36** [comment]
![image](https://github.com/bethylamine/soupcan/assets/54255452/ac214230-104c-444a-b7db-1da46615687c)
Firefox

**Comment by bethylamine** [comment]
Thanks! Could you try re-installing the plugin if you haven't already?

**Comment by hasrock36** [comment]
Yes

**Comment by bethylamine** [comment]
I think I see the issue. Will be fixed (hopefully) in 0.8.2.
