### ISSUE TITLE
Options UI on iOS

### ISSUE THREAD

**Issue by matthewberryman** [bethylamine/soupcan#48]
Could be made more friendly on iOS
I would suggest a collapsible navbar menu like on my [company website](https://acrossthecloud.net) ([code](https://github.com/AcrossTheCloud/acrossthecloud.net)) as well as adjusting the drop-down menus sizing and placement. For development and testing work, instead of Safari on iOS you could use Chrome desktop dev tools and mobile screen options there.
![image](https://github.com/bethylamine/soupcan/assets/2288238/697586b3-e5d2-49eb-8b21-f909bd25e760)
![image](https://github.com/bethylamine/soupcan/assets/2288238/caddac6e-6e4d-4a02-9db2-45af887321e5)
![image](https://github.com/bethylamine/soupcan/assets/2288238/f03ad997-8d66-4398-abb9-ef468763ba24)

**Comment by matthewberryman** [comment]
If you're happy with my suggested approach, I'm happy to work on a PR (usual disclaimer though, I am working on this in my spare time while managing post-stroke fatigue)

**Comment by 0xallie** [comment]
Wait, how did you get it working in Safari on iOS? I tried to install it in Orion but the buttons on the setup page didn't work.

**Comment by matthewberryman** [comment]
@0xallie I converted it to a [iOS/macOS Safari extension](https://github.com/AcrossTheCloud/Soupcan-Safari), with some [tweaks](https://github.com/bethylamine/soupcan/pull/47) (context menus don't work on iOS since there's no right click). You can install and test via the [TestFlight public link](https://testflight.apple.com/join/lcrn6D84)

**Comment by 0xallie** [comment]
Oh nice. Maybe we could actions like reporting into the three-dot menu on tweets/user profiles for iOS?

Orion does support content menus on iOS unlike Safari, but I haven't managed to debug the issue with the buttons during setup not working, since it works fine on Orion macOS and Orion iOS doesn't seem to have any sort of dev tools.

**Comment by bethylamine** [comment]
Made some quick adjustments in caf1dbacb92896efb918ed3e16f919777e514d5c

**Comment by matthewberryman** [comment]
> Maybe we could actions like reporting into the three-dot menu on tweets/user profiles for iOS?

Nice idea, I'll look into it.
