### ISSUE TITLE
Settings are not changed

### ISSUE THREAD

**Issue by 08Juan80** [bethylamine/soupcan#49]
I try to change the extension's settings so it differentiates markings (so I can see which users are in both Shinigami Eyes and Soupcan or either one of them), but it resets back to default upon refreshing the settings page.

**Comment by bethylamine** [comment]
Is this on iOS?

**Comment by 08Juan80** [comment]
No. It's on Chrome in Windows 10.

**Comment by bethylamine** [comment]
Can you verify for me if you something is selected here?

![image](https://github.com/bethylamine/soupcan/assets/130214958/8262fc77-a95d-47d1-9120-08b14475e419)

If not, the options don't save. Fixed in the latest build (see https://github.com/bethylamine/soupcan/issues/52#issuecomment-1612724258)

**Comment by 08Juan80** [comment]
Oh yeah, I had nothing selected there, and now that I did, it's fixed.
