### ISSUE TITLE
Upgrade imagehash-web version to 3.0.1

### ISSUE THREAD

**Issue by simon987** [bethylamine/soupcan#56]
Hi the 3.0.1 version has significant performance improvement for phash (and added crop resistant hash)

**Comment by bethylamine** [comment]
Cool! Do your tests indicate that it returns the same hashes as before?

**Comment by simon987** [comment]
Yes, it returns the exact same hash as before

**Comment by bethylamine** [comment]
Awesome. I'll play around with that and the crop-resistant hash when I get a chance. Thanks!

**Comment by bethylamine** [comment]
![image](https://github.com/bethylamine/soupcan/assets/130214958/2dda9d7c-8064-4372-95df-f8553c775336)

![image](https://github.com/bethylamine/soupcan/assets/130214958/50ab381d-0e34-4741-aba5-ececa1a64abb)

Indeed, looks good!
