### ISSUE TITLE
profile names are flagged red incorrectly when coming from a red profile

### ISSUE THREAD

**Issue by anny-goerl** [bethylamine/soupcan#6]
Browser Chrome on a Mac, Soupcan Version 0.5:

1. Visit https://twitter.com/CSpaulding1312
2. Use the search bar a search for Lthorra
3. Klick [Lthorra Fuxxfell]
4. Username is red

Additional finding, when I copy paste the Lthorra Fuxfell top name, the copied text looks like this: "[Lthorra Fuxxfell](https://twitter.com/CSpaulding1312)"

**Comment by 0xallie** [comment]
I can confirm this, seems like #2 was not fully fixed. I hadn't noticed it myself yet since a fix was pushed out for it.

**Comment by bethylamine** [comment]
Will investigate. thanks!
