### ISSUE TITLE
Suggestion: More "Actions" for expediency.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#62]
Below "Delete report". 

1. A 2nd and 3rd button button for [account] "Does not exist" and [account is] "Currently suspended".
    1. Protected Text. When these options are selected they would be almost the same as "Delete report" except that the first characters would contain non-removeable protected text eg: [Acc does not exist] or [Acc currently suspended]. Moderators would still be able to write other characters after the tag.
1. Similarly a 4th button for "account is currently protected". \
    In the case of "account is protected", this could function to ignore/update but not purge the report from it's **current position** in the queue.
    1. When selected the report remains where it is in the queue, the report is neither validated nor appealed.
    1. Text could be added either under "Who reported?" or next to their username "{moderator name} observed account protected XX:XX XX/XX/XX" indicating when a moderator clicked "account is protected". 
    1.Feature would allow multiple moderators to click the option consecutively, but not more than once per day (button is greyed out if last used within 24 hours). 
    1.New entry for each time a moderator clicks it.
1. "Already flagged" For red accounts which erroneously appear in the queue.

**Comment by bethylamine** [comment]
Hope you don't mind I updated the formatting.

**Comment by CJH87** [comment]
I'd also consider an option for "this account was renamed".

**Comment by bethylamine** [comment]
Update to this:

Feel free to delete reports for accounts that are suspended or protected at your discretion. If they are muddying up the report queue, it's OK to remove them. They will come back eventually, for repeat offenders. N.B. reports for red users will go through now, to add more reasons (but should get auto-approved/not show up in the queue)
