### ISSUE TITLE
Suggestion: Moderators able to view [a list of] accounts they've appealed.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#65]
A "view my appeals" button either under the "moderate reports" in the dialogue in which the latter appears or on the moderate reports page where such a niche feature would be much more tidily placed.

Something to do if the report queue is ever cleared. :p

EDIT: I appreciate that appeals don't prevent users and other moderators re-reporting.

EDIT: To be clear that's account which that moderator appealed, not accounts they marked as transphobes later appealed by another moderator.

**Comment by bethylamine** [comment]
Should be considered in #126 . Closing in favor of that ticket.
