### ISSUE TITLE
Suggestion: Moderators to flag a reported account as consistently non-english/american english. So they and others can leave the report for a moderator capable of dealing with it.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#66]
Yeah; English might not be the most widely spoken language.

(1) I suppose this could be another action: "Account tweets in {langauge drop down}" tooltip something like "Recommend review by moderator fluent in account's language."

(1a) Resulting in the report getting a coloured highlight and a note added that moderators not fluent in the selected language should avoid the report.

I appealed the account (AT M///axim///eH/aes) which prompted me to write this. Their reported tweet was deleted.

**Comment by bethylamine** [comment]
Adding to #126
