### ISSUE TITLE
Concept Discussion: expanded report text for low trust score users.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#70]
I assume this is an appropriate venue for discussion.

An additional or substitude message for users with single digit trust scores (0-9). Probably good idea to draw attention to the fact that it is different.

[EDIT:] On clicking report transpobe this message could appear before the usual report window. [End edit]

"One/Two or more of your recent reports was not found violate the [link] soupcan ToS. Are you sure you want to report this account? Have you considered checking their activity history including tweets, retweets, comments and likes, and perhaps running the soupcan keyword search against their account?"

The One/Two is not actually linked to their recent reports, just used as a figure of speech.

Text variation repeats every 5 accounts they report until their trust rises.

Potentially the same concept for anyone who's trust score is on a consistent downtrend.

**Comment by bethylamine** [comment]
The trust score is intentionally hidden from the client to prevent (or slow down) gaming of the system: i.e. to determine what methods of platform manipulation are successful.
