### ISSUE TITLE
To avoid confusing users, perhaps multiple types of appeals need to be considered.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#74]
I think we definitely need to divide the appeals for the purposes of varying their visibility to standard users. I believe some users may be viewing appealed accounts as having been appealed **after** making it through to being red where the decision to appeal is presumably given a lot more scrutiny. I don't actually know where user appeals of red accounts go (but I assume they're direct to Beth).
____
ToS: "Not worthy of a report by itself: people who are being mean to trans people, asking questions about trans people in potentially clunky language, accidental misgendering, one-off transphobic comments (must be a pattern)."

I look for clear evidence of malice before appealing **when it is not present**. Such comments which an observer would say "if an unstable/uninformed person read that could they believe the writer couldn't **knows** they're creating a risk"). For example if a person says "that's what a paedophile would say". That puts the person they're replying to in danger from any observers that could uncritically take that charged language to mean they were saying "this guy's a pedo lynch please". 

Explicit speech vs insinuated or diplomatic.

We wisely can't flag everyone red. 

____

Some concepts and passing thoughts to show what I'm thinking, in practice this could be a binary dichotomy of Hidden or Visible appeals.

* Appealed (previously red). [Visible to all Soupcan users.]
* Appealed - Overzealous report, at most casual/jovial transphobia from seemingly clean account. [Appealed status only visible to moderators.]
* Appealed - Follows/RTs/Likes seem clean. Comments do not rise to exceeding ignorance. No calls (inc recklessly) for harm to trans people. [Appealed status only visible to moderators.]
* Appealed pre-transphobe - Transphobia present but after 5-8 minutes of inspection certainly doesn't rise to a ToS violation - moderator absolutely believes user will eventually reach that level of output. [Appealed status only visible to moderators.] - In this event I don't believe the reporter should lose trust score.

____
Moderator appeals UI thoughts.

If the account is currently red, and not pending appeal when a moderator interacts, retain the current system.

If the account is not currently red, perhaps augment the appeals process with a popup with affirmation-only (checkbox) questions (left blank = no). Reminder, these questions are posed after the moderator has decided to appeal.

1. Has the Soupcan reporter(s) made a mistake? (No= +1)
2. If scant evidence of transphobia exists on this account: was it rare or hard to find? (Yes= +1) 
3. Does this account follow notable/celebrity transphobes in their visible followers? (Yes= +1)
4. Do RT/Likes suggest this person is sympathetic to transphobic talking points? (Yes= +1)
5. Do you expect this person to be reported again? (Yes= +1)

Only show the account's appealed status to [non-moderator] Soupcan Users if the score is 0.

EDIT: The second question needs rephrasing to make it clear that answering no means no transphobia was found. But that answering yes means that if it was found it **must** have been hard to find.
____

**Comment by bethylamine** [comment]
I think I can partially implement this already, because the system knows the difference between appealed without approved report and appealed after approved report

**Comment by CJH87** [comment]
Any news on this? 

I'm definitely repeating myself below but hopefully much more concisely. :)

I think it would be good for the MH of non-moderator soup can users: if moderators could distinquish these two states and regular users could only see appealed status where the account had recieved a red transphobe flag as a result of an approved report. 

It's definitely demoralising to see comments about an account's appealed status in soup can user submissions to the mod queue. So I imagine it's the same in a gaslighty way for users. Not that these comments are common. 
____
Appealed accounts which were never red should not be psychologically shielded by that appeal status in the eyes of regular users. Or, if they are, it should be clear that this status means they were previously reported by soupcan users and moderators determined the user did not rise above ignorance of trangender subject matter. IMHO just hiding the status would be most expedient.

**Comment by bethylamine** [comment]
I'm considering removing the appealed labelling (gray color) and instead having a mod-only "user history" type visual on a profile.

**Comment by CJH87** [comment]
> I'm considering removing the appealed labelling (gray color) and instead having a mod-only "user history" type visual on a profile.

This would certainly align with how I think it should be.

**Comment by bethylamine** [comment]
Appeal color has been removed. Although appeal reason would be nice, that would be an enhancement and can be created as a separate issue.
