### ISSUE TITLE
Concept. Pride23 Search.

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#75]
Clearly they like to reveal themselves a lot more during pride. Could be a hidden search activated by holding control when clicking on the keyword search - so that UI is unchanged.

Just a shortcut like the keyword search to show the following:

"from:@twitteruser until:2023-07-01 since:2023-06-01 exclude:replies"

So as to inspect their twitter timeline from 1st June 2023 through 1st July 2023 without retweets and replies. I've tried to find the code to show just retweets (via search) but so far that eludes me.

The above parameters appears to include quote tweets.

I'm running into accounts which are highly active but which it's time consuming to substantiate and which appear to be accounts which should be appealed, until I scroll their feeds back to around 20th June.

____

In the meantime I'll be pasting "until:2023-07-01 since:2023-06-01 exclude:replies" over the keyword search when it is inconclusive.

**Comment by 0xallie** [comment]
Good idea.

I don't think search is able to show retweets at all, only QRTs.

**Comment by bethylamine** [comment]
Closing in favor of #114
