### ISSUE TITLE
Data usage considerations

### ISSUE THREAD

**Issue by 0xallie** [bethylamine/soupcan#81]
The Soupcan JSON dataset is currently sitting at 10 MiB, which may be an issue for people using a metered connection with a data cap (e.g. cellular on mobile or even tethered to a computer). Considering currently the database is updated at most once per hour server-side, it may use up to 10 MiB hourly, or 240 MiB daily if you leave X/Twitter open nearly 24/7. But since the local database update interval is 5 minutes, if server-side database updates suddenly start being pushed more often, this data usage can increase 12-fold, up to 120 MiB hourly or nearly 3 GiB daily.

Potential optimizations:
- Enable gzip/brotli compression on AWS (would reduce the transfer size to about 3 MiB)
- Remove extraneous whitespace from the JSON (probably not too significant, only saves about 450 KiB without compression and 10 KiB with)
- Add an option to reduce local update interval or disable automatic updates entirely (in the latter case, adding a reminder if the database hasn't been updated in a while might be a good idea)

**Comment by bethylamine** [comment]
The database is updated once per day now, so it should be 10MiB max daily

All optimizations listed would be good.

**Comment by bethylamine** [comment]
Implemented gzip compression for the data set (reduced size by ~70%, and will reduce growth speed). Will go out with v0.15.0.

**Comment by bethylamine** [comment]
![image](https://github.com/bethylamine/soupcan/assets/130214958/a744d161-3a35-4c42-b20e-777023a1424e)
