### ISSUE TITLE
when reporting a transphobe, a error called "RROR" pops up. 

### ISSUE THREAD

**Issue by Kamisatocest** [bethylamine/soupcan#87]
![Screen Shot 2023-10-08 at 3 12 37 AM](https://github.com/bethylamine/soupcan/assets/103712427/dcc0753a-2736-4c8b-8f49-047f727817fc)

https://github.com/bethylamine/soupcan/assets/103712427/770246b5-1781-49e6-968a-ca0c2494a74c

**Comment by 0xallie** [comment]
Yeah this is an incompatibility with the Old Twitter Layout extension. It should be easy enough to fix, I'll make a PR.
