### ISSUE TITLE
The extension's popup panel shows up clipped on Vivaldi and Edge

### ISSUE THREAD

**Issue by kyranet** [bethylamine/soupcan#90]
<details>
<summary><strong>Image attachments (click to expand)</strong></summary>

Vivaldi | Edge
-- | --
![image](https://github.com/bethylamine/soupcan/assets/24852502/623c7ec6-3ee1-4687-9726-b714700e6434) | ![image](https://github.com/bethylamine/soupcan/assets/24852502/5f250017-49a5-437c-a10d-aca46ed1ab32)

</details>

Other extensions show their respective popup panels correctly, however, Soupcan seems to hide the x overflow, which results on the information getting cut somehow. Edge is a clean install where Soupcan is the only installed extension.

\* I haven't tried on Firefox or any other Chromium browser.

Browser information:

Vivaldi | 6.4.3160.41 (Stable channel) (64-bit)
-- | --
Revision | 5f5f4f3f77914abe3f457c711cf1ebf00d5681ff
OS | Windows 11 Version 22H2 (Build 22621.2506)
JavaScript | V8 11.8.172.17

Microsoft Edge | 118.0.2088.76 (Official build) (64-bit)
-- | --
Revision | d3ddcf1d51d5981b1862597e6ea77f06d265a377
Chromium version | 118.0.5993.118
Operating system | Windows 11 Version 22H2 (Build 22621.2506)
JavaScript | V8 11.8.15.10

**Comment by bethylamine** [comment]
Might just need a css tweak. I'll have to install those browsers to give it a go I think as a workaround, you can use the context menu of the plugin to open the options menu full screen:

![image](https://github.com/bethylamine/soupcan/assets/130214958/092811d2-fb8c-4532-98c6-b0738deabb30)

**Comment by bethylamine** [comment]
(Has this been an issue recently?)

**Comment by kyranet** [comment]
No, it works now as intended, thanks!
![image](https://github.com/bethylamine/soupcan/assets/24852502/4aca73a6-fbc1-407c-b105-0db5094da711)
