### ISSUE TITLE
Are appealed [red] users protected from the automoderation process?

### ISSUE THREAD

**Issue by CJH87** [bethylamine/soupcan#93]
I was going to propose a discussion on whether soupcan could automatically protect accounts with an appeal on file from reports against content which pre-dates the appeal, but I've realised that soupcan likely doesn't scan the links in the reports and on reflection doesn't need to.

However could it be an improvement if red accounts which have been appealed by a moderator were made exempt from automoderation? 

Not exempt from the mod queue or client user's own red lists.

Sort of an insurance that appealed RED users will always have reports against them put in front of a moderator.

Or is this already how it works?

This is a discussion not a feature request.

**Comment by bethylamine** [comment]
Currently there is no double-jeopardy style protection which prevents going from marked to unmarked and vice-versa. This might be a good tie in to #98, in that it might help that these reports are flagged as "must-be-moderator-approved" before they are processed.
