### ISSUE TITLE
Ability to block without showing masked content

### ISSUE THREAD

**Issue by hasrock36** [bethylamine/soupcan#96]
Currently to block an account you have to hover over their tweet withh the mouse, which unveils whatever is masked, a way to block without revealing this would be ideal

**Comment by lovelydumpling** [comment]
100% agreed. Sucks having to expose myself to the transphobia to block the rednames.

**Comment by bethylamine** [comment]
A fix will go out with v0.14.2 which instead just blurs the text, so you can click the context menu on the side without unblurring the content. The transition also gives you a bit more time for you to hover, before it will unblur completely.

Please let me know if this creates any other issues or doesn't work for your use case

![image](https://github.com/bethylamine/soupcan/assets/130214958/00c4bdbd-487e-4489-8e7e-44d351a6200e)
