### ISSUE TITLE
Red tweets not obscured when quoted

### ISSUE THREAD

**Issue by hasrock36** [bethylamine/soupcan#99]
This appears to be new but I've noticed red tweets not being obscured when quoted in the timeline, but if I go to the tweet itself it is obscured, both the quoted tweet, and the quoting tweet.
![image](https://github.com/bethylamine/soupcan/assets/54255452/de5635b4-7b19-48e3-83da-e18d4212c234)
![image](https://github.com/bethylamine/soupcan/assets/54255452/56cf4570-d84c-4ee7-9fa7-279cfa25cbde)
![image](https://github.com/bethylamine/soupcan/assets/54255452/1b99d181-df94-4782-89fd-9dc11c67ae87)

**Comment by bethylamine** [comment]
This does seem to be a regression, thanks for reporting

**Comment by bethylamine** [comment]
I notice that it seems to work, but sometimes the names revert to white (and unblur) until they go red again a few seconds later.

![image](https://github.com/bethylamine/soupcan/assets/130214958/ee5e08d7-87a3-4541-aa2c-77b8fafd98a8)

![image](https://github.com/bethylamine/soupcan/assets/130214958/5f277433-77ab-4673-af64-93fc22bcf1ac)

Hmm.

**Comment by bethylamine** [comment]
Okay, should be fixed in v0.17.1 / https://github.com/bethylamine/soupcan/commit/e412303878e1c8eed22f894d972ec204b07ff138 .
